### ISSUE TITLE
[axarev/parsr:latest] @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0

### ISSUE THREAD

**Issue by poveden** [axa-group/Parsr#70]
**Summary**

The latest version of Parsr published on Docker Hub throws an error when trying to get the queue status for a document previously submitted to the `/document` endpoint.

**Steps To Reproduce**

1. Use the following `docker-compose.yml`:

```yaml
version: '3.3'

services:
  duckling:
    image: axarev/duckling:latest
    ports:
      - 8000:8000

  parsr:
    image: axarev/parsr:latest
    ports:
      - 8080:3000
      - 3001:3001
    environment:
      DUCKLING_HOST: http://duckling:8000
      ABBYY_SERVER_URL:
    volumes:
      - ./pipeline/:/opt/app-root/src/demo/web-viewer/pipeline/

volumes:
  pipeline:
    driver: local
```

2. Run `docker-compose up`.
3. Call `POST http://localhost:3001/api/document` with a sample PDF and the ["exempli gratia" `config.json`](https://github.com/axa-group/Parsr/blob/develop/docs/configuration-file.md#5-exempli-gratia) file.
4. Call `GET http://localhost:3001/api/queue/{id}` with the ID produced at step 3.

**Expected behavior**
Get an [appropriate response](https://github.com/axa-group/Parsr/blob/develop/docs/api-guide.md#2-get-the-queue-status-get-queueid).

**Actual behavior**
An `HTTP 500 Internal Server Error` is received with the following payload:

```
/opt/app-root/src/node_modules/@grpc/grpc-js/build/src/index.js:47
throw new Error(`@grpc/grpc-js only works on Node ${supportedNodeVersions}`);
^

Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
at Object.<anonymous> (/opt/app-root/src/node_modules/@grpc/grpc-js/build/src/index.js:47:11)
	at Module._compile (module.js:652:30)
	at Object.Module._extensions..js (module.js:663:10)
	at Module.load (module.js:565:32)
	at tryModuleLoad (module.js:505:12)
	at Function.Module._load (module.js:497:3)
	at Module.require (module.js:596:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/opt/app-root/src/node_modules/google-gax/build/src/grpc.js:37:14)
		at Module._compile (module.js:652:30)
```

**Environment**
 - Reference commit/version: [axarev/parsr:latest](https://hub.docker.com/layers/axarev/parsr/latest/images/sha256-2cb349e2580c2a6a2ae6977efc793121f3e14a9f4db11888c7714bd6be081e71)
 - OS: Windows 10
 - Docker Desktop Community for Windows:
  - Version: 2.1.0.3 (38240)
  - Engine: 19.03.2
  - Compose: 1.24.1
